//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeAssignment.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string ForeNames { get; set; }
        public string SurName { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public bool Gender { get; set; }
        public string HomeNo { get; set; }
        public string WorkNo { get; set; }
        public string MobileNo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
